### ISSUE TITLE
Edit icon only showing on local install 

### ISSUE THREAD

**Issue by JorisOrangeStudio** [heidkaemper/statamic-toolbar#10]
In the Toolbar Controller this function has a condition that prevents the pencil (edit) icon from loading on environments that are not local. Is it possible to override this or change this? Or can it be removed from the addon? I want to use the toolbar on a production website. 

```
protected function getCpLink(): string|null
    {
        if (! config('statamic.toolbar.components.cp_link', true)) {
            return null;
        }
        if (! auth()->check() && config('app.env') !== 'local') {
            return null;
        }
        return $this->entry?->editUrl();
    }
 ```

**Comment by heidkaemper** [comment]
Changed with release 1.1.2
https://github.com/heidkaemper/statamic-toolbar/releases/tag/1.1.2
