### ISSUE TITLE
Option to hide the toolbar

### ISSUE THREAD

**Issue by heidkaemper** [heidkaemper/statamic-toolbar#2]
Maybe a frontend toggle to hide/show the toolbar?!

**Comment by heidkaemper** [comment]
That feature is part of the 1.0.5 update.
https://github.com/heidkaemper/statamic-toolbar/releases/tag/1.0.5

**Comment by adampatterson** [comment]
Once you hide the toolbar... how do you get it back? 😂

**Comment by heidkaemper** [comment]
@adampatterson Simply move your pointer to the lower left corner. The toolbar should then become visible again.
