### ISSUE TITLE
Hide toolbar inside editor of Live Preview

### ISSUE THREAD

**Issue by JorisOrangeStudio** [heidkaemper/statamic-toolbar#8]
Is it possible to hide the toolbar when viewing the iframe inside the live preview? 
Possibly with the X-Statamic-Live-Preview: 1 headers?

**Comment by heidkaemper** [comment]
Good idea! I'll check that.

**Comment by heidkaemper** [comment]
FYI, the Live-Preview Header doesn't seem to exist anymore. But a condition on query parameters works just fine.

That's includes in the v1.1.1 release:
https://github.com/heidkaemper/statamic-toolbar/releases/tag/1.1.1
